remote_theme: nielsenramon/chalk

# 보안 테마 설정
title: 에브리DAI
description: AI 기반 사이버 보안 전문가를 위한 심화 학습 과정

# 커스텀 CSS 파일 포함
sass:
  style: compressed

# 네비게이션 설정

# 커스텀 CSS 경로 추가 (Jekyll이 이 파일을 로드하도록 설정)
plugins:
  - jekyll-remote-theme
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-assets

# SEO 설정
url: "https://khsqowp.github.io"
baseurl: ""
lang: ko_KR
